version: '3'
services:
    api:
        build: .
        networks:
            - default
        ports:
            - "5000:5000"
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
        networks:
          - default
        ports:
          - 5405:5432
        restart: always